/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Customer.Customer;
import Business.Platform;
import Person.Person;
import Roles.CustomerRole;
import UserAccount.UserAccount;
import UserAccount.UserAccountDirectory;
import Validation.FormatValidate;
import Validation.VerifyNull;
import java.awt.Color;
import java.net.Authenticator;
import javax.mail.PasswordAuthentication;
import java.util.Properties;
import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author forumkaria
 */
public class CustomerRegistrationJPanel extends javax.swing.JPanel {

    private Platform platform;
    private UserAccount ua;
    
    private FormatValidate formatValid;
    private boolean nameValid = false; //no special character
    private boolean emailValid = false; //normal email format
    private boolean phoneValid = false; //10 digits
    
    /**
     * Creates new form RegistrationJPanel
     */
    public CustomerRegistrationJPanel(Platform platform) {
        initComponents();

        this.platform = platform;
        jPanel1.setBackground(new Color(0,0,0,90));
        
        formatValid = new FormatValidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        bgImageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fieldusername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JTextField();
        fieldname = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        filedEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1300, 800));

        bgPanel.setMinimumSize(new java.awt.Dimension(1300, 870));
        bgPanel.setPreferredSize(new java.awt.Dimension(1300, 800));
        bgPanel.setLayout(new java.awt.BorderLayout());

        bgImageLabel.setBackground(new java.awt.Color(204, 204, 255));
        bgImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/mainpage.jpg"))); // NOI18N
        bgPanel.add(bgImageLabel, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(fieldusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 120, 30));
        jPanel1.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 120, 30));

        fieldname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldnameFocusLost(evt);
            }
        });
        jPanel1.add(fieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 120, 30));

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 120, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 20));

        filedEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                filedEmailFocusLost(evt);
            }
        });
        jPanel1.add(filedEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 120, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, 30));

        fieldPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldPhoneFocusLost(evt);
            }
        });
        jPanel1.add(fieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 120, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Explorers");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 270, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bgPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 812, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public static void sendEmail(String to, String subject, String body) {
        // Sender email configuration
//        String senderEmail = "exploreease.noreply@gmail.com";
//        String senderPassword = "Password12#34";

          String senderEmail = "exploreease.noreply@gmail.com";
          String senderPassword = "Password12#34";

        // Recipient email configuration
        String recipientEmail = to;

        // Email server configuration
        String host = "smtp.gmail.com";
        int port = 587;

        // Set properties
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", port);

        // Create session
         // Create session
        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(senderEmail, senderPassword);
            }
        });

        try {
            InternetAddress fromAddress = new InternetAddress(senderEmail);
            InternetAddress toAddress = new InternetAddress(recipientEmail);

            Message message = new MimeMessage(session);
            message.setFrom(fromAddress);
            message.setRecipient(Message.RecipientType.TO, toAddress);
            message.setSubject(subject);
            message.setText(body);
            Transport.send(message);

        } catch (MessagingException ex) {
            ex.printStackTrace();
        }
    }

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory uad = this.platform.getUad();

        //get customer information
        String userName = fieldusername.getText();
        String pass = fieldPassword.getText();
        String name = fieldname.getText();
        String email = filedEmail.getText();
        String phone = fieldPhone.getText();

        //check null fields
        VerifyNull checkNull = new VerifyNull();
        boolean nonull = checkNull.checkNullObject(userName,pass,name, email, phone);
        if(nonull){
            //check input format
            if (!nameValid){
                JOptionPane.showMessageDialog(null,"Check name format");
            }else if(!emailValid){
                JOptionPane.showMessageDialog(null,"Check email format");
            }else if(!phoneValid){
                JOptionPane.showMessageDialog(null,"Check phone format");
            }
            //check user account unique
            else if(!uad.checkUserNameUnique(userName)) {
                JOptionPane.showMessageDialog(null, "Credentials are taken. Try again!");
            }
            //create user account
            else {
                UserAccount user = uad.createUserAccount(userName, pass,new CustomerRole());
                Person p = this.platform.getPersonDirectory().createPerson(user.getAccountId(), name);
                Customer c = this.platform.getCustomerDirectory().createCustomer(p, user);
//                sendEmail("saakethlogs@gmail.com","Welcome to ExploreEase !!","We are glad to welcome you into our One Stop Solution for all your Travel plans. Happy Travelling with Ease! \n - ExploreEase Team");
                JOptionPane.showMessageDialog(null, "Registered Successfully");
            }
        }
        
    }//GEN-LAST:event_registerBtnActionPerformed

    private void fieldnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldnameFocusLost
        // TODO add your handling code here:
        if(formatValid.validateName(fieldname.getText())){
            this.nameValid = true;
        }
    }//GEN-LAST:event_fieldnameFocusLost

    private void filedEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_filedEmailFocusLost
        // TODO add your handling code here:
        if(formatValid.validateEmail(filedEmail.getText())){
            this.emailValid = true;
        }
    }//GEN-LAST:event_filedEmailFocusLost

    private void fieldPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPhoneFocusLost
        // TODO add your handling code here:
        if(formatValid.validatePhone(fieldPhone.getText())){
            this.phoneValid = true;
        }
    }//GEN-LAST:event_fieldPhoneFocusLost
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImageLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldname;
    private javax.swing.JTextField fieldusername;
    private javax.swing.JTextField filedEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables
}
