/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Customer.Customer;
import Business.Employee.Employee;
import Business.Enterprise.EnterpriseDirectory;
import Business.Organization.HotelOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Platform;
import Person.Person;
import Roles.AirlineAgentRole;
import Roles.AttractionOfficerRole;
import Roles.CustomerRole;
import Roles.FoodServiceSupplierRole;
import Roles.HotelManagerRole;
import Roles.InsuranceAdvisorRole;
import Roles.Role;
import Roles.TravelAgentRole;
import UserAccount.UserAccount;
import UserAccount.UserAccountDirectory;
import Validation.VerifyNull;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author forumkaria
 */
public
        class EmployeeRegistrationJPanel extends javax.swing.JPanel {
    private Platform platform;
    private UserAccount ua;
    
    /**
     * Creates new form EmployeeRegistrationJPanel
     */
    public
            EmployeeRegistrationJPanel(Platform platform) {
        initComponents();
        
        this.setVisible(true);
        this.platform = platform;
//        jPanel1.setBackground(new Color(0,0,0,90));
        
        jComboBox.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        fieldusername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JTextField();
        fieldname = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        filedEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        bgPanel = new javax.swing.JPanel();
        bgImageLabel = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(fieldusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 120, 30));
        jPanel2.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 120, 30));
        jPanel2.add(fieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 120, 30));

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel2.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        jLabel2.setText("Password:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 20));

        jLabel6.setText("Username:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, 20));

        jLabel7.setText("Name:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, 20));

        jLabel8.setText("Email:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 20));
        jPanel2.add(filedEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 120, 30));

        jLabel9.setText("Organization:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, 30));
        jPanel2.add(fieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 120, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Explorers");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 270, 40));

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Airline", "Hotel", "Travel Agency", "Attraction", "Food Service", "Insurance" }));
        jPanel2.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 120, 30));

        jLabel10.setText("Phone:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, 30));

        bgPanel.setLayout(new java.awt.BorderLayout());

        bgImageLabel.setBackground(new java.awt.Color(204, 204, 255));
        bgPanel.add(bgImageLabel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(224, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(217, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(39, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(275, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory uad = this.platform.getUad();
        EnterpriseDirectory enterpriseDirectory = this.platform.getEnterpriseDirectory();

        //get customer information
        String userName = fieldusername.getText();
        String pass = fieldPassword.getText();
        String name = fieldname.getText();
        String email = filedEmail.getText();
        String phone = fieldPhone.getText();
        String organization = (String) jComboBox.getSelectedItem();

        //check null fields
        VerifyNull checkNull = new VerifyNull();
        boolean nonull = checkNull.checkNullObject(userName,pass,name, email, phone);
        if(nonull){
            //check user account unique
            if(!uad.checkUserNameUnique(userName)) {
                JOptionPane.showMessageDialog(null, "Credentials are taken. Try again!");
            }
            //create user account
            else {
                Role role;
                Organization org;
                
                switch (organization) {
                    case "Hotel":
                        role = new HotelManagerRole();
                        org = enterpriseDirectory.findEnterprise("enterprise2").getOrganizationDirectory().findOrganization("org3");
                        break;
                    case "Airline":
                        role = new AirlineAgentRole();
                           org = enterpriseDirectory.findEnterprise("enterprise1").getOrganizationDirectory().findOrganization("org1");
                        break;
                    case "Insurance":
                        role = new InsuranceAdvisorRole();
                        org = enterpriseDirectory.findEnterprise("enterprise3").getOrganizationDirectory().findOrganization("org5");
                        break;
                    case "Food Service":
                        role = new FoodServiceSupplierRole();
                        org = enterpriseDirectory.findEnterprise("enterprise1").getOrganizationDirectory().findOrganization("org2");
                        break;
                    case "Attraction":
                        role = new AttractionOfficerRole();
                        org = enterpriseDirectory.findEnterprise("enterprise4").getOrganizationDirectory().findOrganization("org6");
                        break;
                    case "Travel Agency":
                        role = new TravelAgentRole();
                        org = enterpriseDirectory.findEnterprise("enterprise3").getOrganizationDirectory().findOrganization("org4");
                        break;
                               
                    default:
                        throw new AssertionError();
                }
//                UserAccount user = uad.createUserAccount(userName, pass,role); 
                //create the employee inside the org's UAD, not the platform's UAD
                UserAccount user = org.getUserAccountDirectory().createUserAccount(userName, pass,role);
                Person p = this.platform.getPersonDirectory().createPerson(user.getAccountId(), name);
                Employee e = org.getEmployeeDirectory().createEmployee(org.getOrganizationId(),p,user);
                JOptionPane.showMessageDialog(null, "Employee Registration Request Sent");
            }
        }

    }//GEN-LAST:event_registerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImageLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldname;
    private javax.swing.JTextField fieldusername;
    private javax.swing.JTextField filedEmail;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables
}
