/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Platform;
import UserAccount.UserAccount;
import UserAccount.UserAccountDirectory;
import VerifyNull.VerifyNull;
import javax.swing.JOptionPane;

/**
 *
 * @author forumkaria
 */
public
        class RegistrationJPanel extends javax.swing.JPanel {
    private Platform platform;
//    private UserAccount ua;
    
    /**
     * Creates new form RegistrationJPanel
     */
    public
            RegistrationJPanel(Platform platform) {
        initComponents();
        
        this.platform = platform;
        
        populateroleCombo();
        comboRole.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldusername1 = new javax.swing.JTextField();
        fieldPassword1 = new javax.swing.JTextField();
        fieldname1 = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboRole = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fieldusername = new javax.swing.JTextField();
        registerBtn1 = new javax.swing.JButton();
        fieldpassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 153));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(fieldusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 120, 30));
        jPanel1.add(fieldPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 120, 30));
        jPanel1.add(fieldname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 120, 30));

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        jLabel5.setText("role");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, 20));

        jLabel2.setText("password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 20));

        jLabel6.setText("username");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 20));

        comboRole.setToolTipText("");
        jPanel1.add(comboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 120, 30));

        jLabel7.setText("name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, 20));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Big Caslon", 1, 18)); // NOI18N
        jLabel1.setText("WELCOME");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 130, 40));

        jLabel3.setText("PASSWORD");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        loginBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 160, 40));

        jLabel4.setText("USERNAME");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        fieldusername.setBackground(new java.awt.Color(204, 204, 204));
        fieldusername.setToolTipText("");
        fieldusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldusernameActionPerformed(evt);
            }
        });
        jPanel2.add(fieldusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 162, 168, 42));

        registerBtn1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        registerBtn1.setText("REGISTER");
        jPanel2.add(registerBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 160, 40));

        fieldpassword.setBackground(new java.awt.Color(204, 204, 204));
        fieldpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(fieldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 235, 168, 42));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 240, 770, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory uad = this.platform.getUad();

        //get user account information
        String userName = fieldusername1.getText();
        String pass = fieldPassword1.getText();

        //get employee information
        String name = fieldname1.getText();
        String role = (String) comboRole.getSelectedItem();
       
        //check null fields
        VerifyNull checkNull = new VerifyNull();
        boolean nonull = checkNull.checkNullObject(userName,pass,name,role);
        if(nonull){
            //check user account unique
        if(!uad.checkUserNameUnique(userName)) {
            JOptionPane.showMessageDialog(null, "Sorry username is taken.");
        }
        //create user account and employee profile
        else {
            if (role.equals("student")){
                UserAccount user = uad.createUserAccount(userName, pass, new StudentRole());
                Student s = this.platform.getSd().createStudent(user.getAccountId(), name);
                JOptionPane.showMessageDialog(null, "User created");

            } else if(role.equals("professor")){
                UserAccount user = uad.createUserAccount(userName, pass, new ProfessorRole());
                Professor p = this.platform.getPd().createProfessor(user.getAccountId(), name);
                JOptionPane.showMessageDialog(null, "User created");
            }
            
        }
        }
        
    }//GEN-LAST:event_registerBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String username = fieldusername.getText();
        String password = fieldpassword.getText();
        //        String role = (String) roleCombo.getSelectedItem();
        VerifyNull checkNull = new VerifyNull();
        boolean nonull = checkNull.checkNullObject(username,password);
        if(nonull){
            if(this.platform.getUad().accountExists(username, password)){
                UserAccount user = this.platform.getUad().getUserAccount(username, password);

                //get work area panel
                user.getRole().createWorkArea(this.platform, user);

                Window frame = SwingUtilities.windowForComponent((Component) evt.getSource());
                frame.setVisible(false);
                this.setVisible(false);

            }else{
                JOptionPane.showMessageDialog(null, "Invalid credentials");
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void fieldusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldusernameActionPerformed

    private void fieldpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldpasswordActionPerformed
        public void populateroleCombo(){
            comboRole.removeAllItems();
            comboRole.addItem("student");
            comboRole.addItem("professor");   
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JTextField fieldPassword1;
    private javax.swing.JTextField fieldname1;
    private javax.swing.JTextField fieldpassword;
    private javax.swing.JTextField fieldusername;
    private javax.swing.JTextField fieldusername1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton registerBtn1;
    // End of variables declaration//GEN-END:variables
}
