/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Platform;
import Person.Person;
import Roles.EnterpriseAdminRole;
import UserAccount.UserAccount;
import UserAccount.UserAccountDirectory;
import Validation.VerifyNull;
import WorkRequest.TripPlanningWorkRequest;
import WorkRequest.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emi
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    Platform platform;
    UserAccount ua;
    JPanel container;
    DefaultTableModel entTable;
    
    public ManageEnterpriseJPanel(JPanel container, Platform platform, UserAccount ua) {
        initComponents();
        this.setVisible(true);
        
        this.platform = platform; 
        this.container = container;
        this.ua = ua;
        this.entTable = (DefaultTableModel) ent.getModel();
        populateTable();
    }

    public void populateTable() {
        entTable.setRowCount(0);
        ArrayList<Enterprise> en = this.platform.getEnterpriseDirectory().getEnterpriseList();
        if (en.size() > 0) {
            for ( Enterprise e: en) {
                for (UserAccount usera: e.getUserAccountDirectory().getUseraccountList()){
                    
                    Object[] row = new Object[4];
                    row[0] = e.getClass().getSimpleName();
                    row[1] = usera.getAccountId();
                    row[2] = usera.getUsername();
                    row[3] = usera.getPassword(); 
                    entTable.addRow(row);
                }
                
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ent = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addOrgnManagerBtn = new javax.swing.JButton();
        managerName = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        updatePass = new javax.swing.JTextField();
        updateOrgnManagerBtn = new javax.swing.JButton();
        deleteOrgManager = new javax.swing.JButton();
        deleteOrgnBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        ent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Enterprise", "Admin Id", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(ent);

        jLabel4.setText("Password:");

        jLabel3.setText("Username:");

        jLabel2.setText("Name:");

        addOrgnManagerBtn.setText("ADD EMPLOYEE");
        addOrgnManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrgnManagerBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Update Password:");

        updateOrgnManagerBtn.setText("UPDATE PASSWORD");
        updateOrgnManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOrgnManagerBtnActionPerformed(evt);
            }
        });

        deleteOrgManager.setText("DELETE EMPLOYEE");
        deleteOrgManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrgManagerActionPerformed(evt);
            }
        });

        deleteOrgnBtn.setText("DELETE ORGANIZATION");
        deleteOrgnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrgnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteOrgManager, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(updatePass)
                        .addComponent(updateOrgnManagerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deleteOrgnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addOrgnManagerBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(57, 57, 57)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(managerName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(managerName)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addOrgnManagerBtn)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateOrgnManagerBtn)
                        .addGap(50, 50, 50)
                        .addComponent(deleteOrgManager)
                        .addGap(18, 18, 18)
                        .addComponent(deleteOrgnBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addOrgnManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrgnManagerBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = ent.getSelectedRow();
        if(selectedRow>=0){
            Enterprise entSelected = this.platform.getEnterpriseDirectory().findEnterpriseByType((String) ent.getValueAt(selectedRow, 0));
        
            String name = managerName.getText();
            String user = username.getText();
            String pass = password.getText();
            
            VerifyNull checkNull = new VerifyNull();
            boolean nonull = checkNull.checkNullObject(name,user,pass);
            if(nonull){
//            UserAccount userCreated = entSelected.getUserAccountDirectory().findById(user);
            Boolean usernameUnique = this.platform.getEnterpriseDirectory().checkUsernameUniqueAcrossEnts(user);
            if (usernameUnique) {
                UserAccount userCreated = entSelected.getUserAccountDirectory().createUserAccount(user, pass, new EnterpriseAdminRole());
                Person entManagerPerson = this.platform.getPersonDirectory().createPerson(userCreated.getAccountId(), managerName.getText());
                
                populateTable();
            }else {
                JOptionPane.showMessageDialog(null, "Username taken!");
            }}
        } else {
            JOptionPane.showMessageDialog(null, "Select an Enterprise!");

        }
        

    }//GEN-LAST:event_addOrgnManagerBtnActionPerformed

    private void updateOrgnManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOrgnManagerBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = ent.getSelectedRow();

        if (selectedRow > -1) {
            
            VerifyNull checkNull = new VerifyNull();
            boolean nonull = checkNull.checkNullObject(updatePass.getText());
        
            if(nonull){
            Enterprise entSelected = this.platform.getEnterpriseDirectory().findEnterpriseByType((String) ent.getValueAt(selectedRow, 0));
            String username = (String) ent.getValueAt(selectedRow, 2);

            UserAccount uaSelected = entSelected.getUserAccountDirectory().findByUserName(username);
            uaSelected.setPassword(updatePass.getText());

            populateTable();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select an Enterprise!");

        }
    }//GEN-LAST:event_updateOrgnManagerBtnActionPerformed

    private void deleteOrgManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrgManagerActionPerformed
        // TODO add your handling code here:

        int selectedRow = ent.getSelectedRow();

        if (selectedRow > -1) {
            Enterprise entSelected = this.platform.getEnterpriseDirectory().findEnterpriseByType((String) ent.getValueAt(selectedRow, 0));
            String username = (String) ent.getValueAt(selectedRow, 2);

            
            UserAccount uaSelected = entSelected.getUserAccountDirectory().findByUserName(username);
            entSelected.getUserAccountDirectory().getUseraccountList().remove(uaSelected);

            populateTable();

        } else {
            JOptionPane.showMessageDialog(null, "Select an Enterprise!");

        }
    }//GEN-LAST:event_deleteOrgManagerActionPerformed

    private void deleteOrgnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrgnBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = ent.getSelectedRow();
        if (selectedRow > -1) {
            Enterprise entSelected = this.platform.getEnterpriseDirectory().findEnterpriseByType((String) ent.getValueAt(selectedRow, 0));
//            Organization o = this.en.getOrganizationDirectory().findOrganizationByType(orgName);
            this.platform.getEnterpriseDirectory().getEnterpriseList().remove(entSelected);

            populateTable();

        } else {
            JOptionPane.showMessageDialog(null, "Select an Enterprise!");

        }
    }//GEN-LAST:event_deleteOrgnBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrgnManagerBtn;
    private javax.swing.JButton deleteOrgManager;
    private javax.swing.JButton deleteOrgnBtn;
    private javax.swing.JTable ent;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField managerName;
    private javax.swing.JTextField password;
    private javax.swing.JButton updateOrgnManagerBtn;
    private javax.swing.JTextField updatePass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
