package UI.OrgManagerWorkArea;

import Business.Organization.Organization;
import Business.Platform;
import Business.Product.FlightTicketProduct;
import Business.Product.Product;
import UserAccount.UserAccount;
import Validation.VerifyNull;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 15512
 */
public class AirlineManagerProductWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AirlineManagerWorkArea
     */
    Platform platform;
    UserAccount ua;
    JPanel container;
    Organization org;
    DefaultTableModel prodTable;

    public AirlineManagerProductWorkArea(Platform platform, JPanel container, UserAccount ua) {
        initComponents();
        this.platform = platform;
        this.container = container;
        this.ua = ua;
        this.org = platform.findOrgByUserAccount(ua.getUsername(), ua.getPassword());
        this.prodTable = (DefaultTableModel) flights.getModel();
        populateFlights();
    }

    public void populateFlights() {
        prodTable.setRowCount(0);

        ArrayList<Product> flights = this.org.getProductCatalog().getProducts();

        if (flights.size() > 0) {
            for (Product flight : flights) {
                FlightTicketProduct f = (FlightTicketProduct) flight.getProductDetails();
                Object[] row = new Object[9];
                row[0] = f;
                row[1] = f.getDepartureCity();
                row[2] = f.getDestinationCity();
                row[3] = f.getAirline();
                row[4] = f.getDepartureDate();
                row[5] = f.getDepartureTime();
                row[6] = f.getFlightDuration();
                row[7] = f.getNonStop();
                row[8] = f.getNumberOfSeatsAvailable();

                prodTable.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        flights = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        depCity = new javax.swing.JTextField();
        seats = new javax.swing.JTextField();
        select = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        desCity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        airline = new javax.swing.JTextField();
        duration = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        departureTime = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nonStop = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        departureDate = new com.toedter.calendar.JDateChooser();
        bgPanel = new javax.swing.JPanel();
        bgImageLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1300, 870));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight ID", "Departure City", "Destination City", "Airline", "Departure Date", "Departure TIme", "Flight Duration", "Non Stop", "Seats "
            }
        ));
        jScrollPane2.setViewportView(flights);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 880, 340));

        jLabel1.setText("Non-Stop");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 426, 80, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("AIRLINE FLIGHT MANAGEMENT");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 27, -1, 20));

        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton4.setText("Remove Flight");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, 150, 60));

        depCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depCityActionPerformed(evt);
            }
        });
        add(depCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 72, 140, 30));

        seats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsActionPerformed(evt);
            }
        });
        add(seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 396, 140, 30));

        select.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        select.setText("Select Flight");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 130, 60));

        jLabel4.setText("Departure City");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(941, 36, 110, 40));

        jLabel7.setText("Departure Date");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(945, 216, 110, 30));

        jLabel8.setText("Destination City");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 106, 120, 20));

        desCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desCityActionPerformed(evt);
            }
        });
        add(desCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 132, 140, 30));

        jLabel9.setText("Airline");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(941, 166, 60, 20));

        airline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlineActionPerformed(evt);
            }
        });
        add(airline, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 186, 140, 30));

        duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationActionPerformed(evt);
            }
        });
        add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 346, 140, 30));

        jLabel10.setText("Seats");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 376, 50, 20));

        departureTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureTimeActionPerformed(evt);
            }
        });
        add(departureTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 296, 140, 30));

        jLabel11.setText("Departure Time");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 276, 110, 20));

        jLabel12.setText("Duration");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(945, 326, 70, 20));

        nonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonStopActionPerformed(evt);
            }
        });
        add(nonStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 423, 30, 30));

        jButton6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton6.setText("Update Flight");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 459, 150, 60));
        add(departureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 246, 140, -1));

        bgPanel.setMaximumSize(new java.awt.Dimension(1300, 870));
        bgPanel.setPreferredSize(new java.awt.Dimension(1300, 870));
        bgPanel.setLayout(new java.awt.BorderLayout());

        bgImageLabel.setBackground(new java.awt.Color(204, 204, 255));
        bgImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sebastien-goldberg-t9IrzQ-38Tk-unsplash.jpg"))); // NOI18N
        bgImageLabel.setMaximumSize(new java.awt.Dimension(1300, 870));
        bgImageLabel.setMinimumSize(new java.awt.Dimension(1300, 870));
        bgImageLabel.setPreferredSize(new java.awt.Dimension(1300, 870));
        bgPanel.add(bgImageLabel, java.awt.BorderLayout.CENTER);

        add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 1290, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void depCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depCityActionPerformed

    private void seatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsActionPerformed

    private void desCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desCityActionPerformed

    private void airlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlineActionPerformed

    private void durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationActionPerformed

    private void departureTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureTimeActionPerformed

    private void nonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nonStopActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        int selectedRow = flights.getSelectedRow();
        if (selectedRow > -1) {
        FlightTicketProduct f = (FlightTicketProduct) prodTable.getValueAt(selectedRow, 0);
            depCity.setText(f.getDepartureCity());
            airline.setText(f.getAirline());
            departureDate.setDate(f.getDepartureDate());
            departureTime.setText(f.getDepartureTime());
            desCity.setText(f.getDestinationCity());
            duration.setText(f.getFlightDuration());
            nonStop.setEnabled(f.getNonStop());
            seats.setText(String.valueOf(f.getNumberOfSeatsAvailable()));

        } else {
            JOptionPane.showMessageDialog(null, "Select a Work request!");

        }
    }//GEN-LAST:event_selectActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int selectedRow = flights.getSelectedRow();
        if (selectedRow > -1) {
        FlightTicketProduct f = (FlightTicketProduct) prodTable.getValueAt(selectedRow, 0);

        VerifyNull checkNull = new VerifyNull();
        boolean nonull = checkNull.checkNullObject(depCity.getText(),desCity.getText(),airline.getText(),departureDate.getDate(),departureTime.getText(),duration.getText(),seats.getText());
        
        if(nonull){
            f.setDepartureCity(depCity.getText());
            f.setDestinationCity(desCity.getText());
            f.setAirline(airline.getText());
            f.setDepartureDate(departureDate.getDate());
            f.setDepartureTime(departureTime.getText());
            f.setFlightDuration(duration.getText());
            f.setNumberOfSeatsAvailable(Integer.valueOf(seats.getText()));
            populateFlights();
        }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Work request!");

        }
        // Others to add
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = flights.getSelectedRow();
        if (selectedRow > -1) {
        FlightTicketProduct f = (FlightTicketProduct) prodTable.getValueAt(selectedRow, 0);
            this.org.getProductCatalog().getProducts().remove(f);
            populateFlights();

        } else {
            JOptionPane.showMessageDialog(null, "Select a Work request!");

        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airline;
    private javax.swing.JLabel bgImageLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JTextField depCity;
    private com.toedter.calendar.JDateChooser departureDate;
    private javax.swing.JTextField departureTime;
    private javax.swing.JTextField desCity;
    private javax.swing.JTextField duration;
    private javax.swing.JTable flights;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox nonStop;
    private javax.swing.JTextField seats;
    private javax.swing.JButton select;
    // End of variables declaration//GEN-END:variables

}
