package UI.OrgManagerWorkArea;
import Business.Organization.Organization;
import Business.Platform;
import Business.Product.AttractionProduct;
import Business.Product.FlightTicketProduct;
import Business.Product.HotelRoomsProduct;
import Business.Product.Product;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 15512
 */
public class AttractionManagerProductWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AirlineManagerWorkArea
     */
    
    Platform platform;
    UserAccount ua;
    JPanel container;
    Organization org;
    DefaultTableModel prodTable;

    public AttractionManagerProductWorkArea(Platform platform,JPanel container, UserAccount ua) {
        initComponents();
        this.platform = platform; 
        this.container = container;
        this.ua = ua;
        this.org = platform.findOrgByUserAccount(ua.getUsername(), ua.getPassword());
        this.prodTable = (DefaultTableModel) products.getModel();
        populateTickets();
    }

     public void populateTickets() {
        prodTable.setRowCount(0);

        ArrayList<Product> products = this.org.getProductCatalog().getProducts();

        if (products.size() > 0) {
            for (Product p : products) {
                AttractionProduct f = (AttractionProduct) p.getProductDetails();
                Object[] row = new Object[4];
                row[0] = f;
                row[1] = f.getCity();
                row[2] = f.getTicketType();
                row[3] = f.getPrice();
                prodTable.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        products = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        desCity = new javax.swing.JTextField();
        select = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        ticket = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(1300, 553));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "City", "Ticket Type", "Price"
            }
        ));
        jScrollPane2.setViewportView(products);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 570, 280));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tourist Attraction Ticket Management");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setText("Remove Ticket");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 120, -1));

        desCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desCityActionPerformed(evt);
            }
        });
        add(desCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 120, -1));

        select.setBackground(new java.awt.Color(204, 255, 204));
        select.setText("Select Ticket");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 130, 40));

        jLabel4.setText("City");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, -1, -1));

        jLabel7.setText("Price");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, -1, -1));

        jLabel9.setText("Ticket Type");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, -1, -1));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 120, -1));

        jButton6.setBackground(new java.awt.Color(204, 255, 255));
        jButton6.setText("Update Ticket");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 120, -1));

        ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketActionPerformed(evt);
            }
        });
        add(ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void desCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desCityActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        int selectedRow = products.getSelectedRow();
        AttractionProduct f = (AttractionProduct) prodTable.getValueAt(selectedRow, 0);
        desCity.setText(f.getCity());
        ticket.setText(f.getTicketType());     
        price.setText(String.valueOf(f.getPrice()));
    }//GEN-LAST:event_selectActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int selectedRow = products.getSelectedRow();
        AttractionProduct f = (AttractionProduct) prodTable.getValueAt(selectedRow, 0);
        
        f.setCity(desCity.getText());
        f.setTicketType(ticket.getText());
        f.setPrice(Integer.valueOf(price.getText()));
        populateTickets();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = products.getSelectedRow();
        AttractionProduct f = (AttractionProduct) prodTable.getValueAt(selectedRow, 0);
        this.org.getProductCatalog().getProducts().remove(f);
        populateTickets();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField desCity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField price;
    private javax.swing.JTable products;
    private javax.swing.JButton select;
    private javax.swing.JTextField ticket;
    // End of variables declaration//GEN-END:variables

}
