/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.OrgManagerWorkArea;

import Business.Organization.Organization;
import Business.Platform;
import Business.Product.FoodServiceProduct;
import Business.Product.Product;
import UserAccount.UserAccount;
import Validation.VerifyNull;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author forumkaria
 */
public class FoodManagerProductWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form FoodManagerProductWorkArea
     */
    Platform platform;
    UserAccount ua;
    JPanel container;
    Organization org;
    DefaultTableModel prodTable;

    public FoodManagerProductWorkArea(Platform platform, JPanel container, UserAccount ua) {
        initComponents();
        this.platform = platform;
        this.container = container;
        this.ua = ua;
        this.org = platform.findOrgByUserAccount(ua.getUsername(), ua.getPassword());
        this.prodTable = (DefaultTableModel) products.getModel();
        populateFoodService();
    }

    public void populateFoodService() {
        prodTable.setRowCount(0);

        ArrayList<Product> foodServices = this.org.getProductCatalog().getProducts();

        if (foodServices.size() > 0) {
            for (Product p : foodServices) {
                FoodServiceProduct f = (FoodServiceProduct) p.getProductDetails();
                Object[] row = new Object[3];
                row[0] = f;
                row[1] = f.getMenu();
                row[2] = f.getPrice();
                prodTable.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        products = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        removeFoodBtn = new javax.swing.JButton();
        menu = new javax.swing.JTextField();
        select = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        updateFoodBtn = new javax.swing.JButton();
        bgPanel = new javax.swing.JPanel();
        bgImageLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1300, 870));
        setPreferredSize(new java.awt.Dimension(1300, 870));

        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 870));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 870));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product ID", "Menu", "Price"
            }
        ));
        jScrollPane2.setViewportView(products);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 570, 280));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FOOD SERVICE MANAGEMENT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        removeFoodBtn.setText("Remove Food Service");
        removeFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFoodBtnActionPerformed(evt);
            }
        });
        jPanel1.add(removeFoodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 160, -1));

        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 160, -1));

        select.setText("Select Food Service");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jPanel1.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 160, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MENU");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 60, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRICE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 270, 60, -1));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 160, -1));

        updateFoodBtn.setText("Update Food Service");
        updateFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFoodBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateFoodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 160, -1));

        bgPanel.setMinimumSize(new java.awt.Dimension(1300, 870));
        bgPanel.setPreferredSize(new java.awt.Dimension(1300, 870));
        bgPanel.setLayout(new java.awt.BorderLayout());

        bgImageLabel.setBackground(new java.awt.Color(204, 204, 255));
        bgImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nahima-aparicio-ERa6eet3nuY-unsplash.jpg"))); // NOI18N
        bgImageLabel.setMaximumSize(new java.awt.Dimension(1300, 870));
        bgImageLabel.setMinimumSize(new java.awt.Dimension(1300, 870));
        bgImageLabel.setPreferredSize(new java.awt.Dimension(1300, 870));
        bgPanel.add(bgImageLabel, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 870));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFoodBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = products.getSelectedRow();
        if (selectedRow > -1) {
        FoodServiceProduct f = (FoodServiceProduct) prodTable.getValueAt(selectedRow, 0);
            this.org.getProductCatalog().getProducts().remove(f);
            populateFoodService();

        } else {
            JOptionPane.showMessageDialog(null, "Select a Work request!");

        }

    }//GEN-LAST:event_removeFoodBtnActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        int selectedRow = products.getSelectedRow();
        FoodServiceProduct f = (FoodServiceProduct) prodTable.getValueAt(selectedRow, 0);
        if (selectedRow > -1) {
            menu.setText(f.getMenu());
            price.setText(String.valueOf(f.getPrice()));

        } else {
            JOptionPane.showMessageDialog(null, "Select a Work request!");

        }

    }//GEN-LAST:event_selectActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void updateFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFoodBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = products.getSelectedRow();
        if (selectedRow > -1) {
        FoodServiceProduct f = (FoodServiceProduct) prodTable.getValueAt(selectedRow, 0);
        
        
            VerifyNull checkNull = new VerifyNull();
            boolean nonull = checkNull.checkNullObject(menu.getText(),price.getText());
        
            if(nonull){
                f.setMenu(menu.getText());
                f.setPrice(Integer.valueOf(price.getText()));
            
                populateFoodService();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Work request!");

        }

    }//GEN-LAST:event_updateFoodBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImageLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField menu;
    private javax.swing.JTextField price;
    private javax.swing.JTable products;
    private javax.swing.JButton removeFoodBtn;
    private javax.swing.JButton select;
    private javax.swing.JButton updateFoodBtn;
    // End of variables declaration//GEN-END:variables
}
