package UI.OrgManagerWorkArea;
import Business.Organization.Organization;
import Business.Platform;
import Business.Product.FlightTicketProduct;
import Business.Product.HotelRoomsProduct;
import Business.Product.Product;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 15512
 */
public class HotelManagerProductWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AirlineManagerWorkArea
     */
    
    Platform platform;
    UserAccount ua;
    JPanel container;
    Organization org;
    DefaultTableModel prodTable;

    public HotelManagerProductWorkArea(Platform platform,JPanel container, UserAccount ua) {
        initComponents();
        this.platform = platform; 
        this.container = container;
        this.ua = ua;
        this.org = platform.findOrgByUserAccount(ua.getUsername(), ua.getPassword());
        this.prodTable = (DefaultTableModel) flights.getModel();
        populateRooms();
    }

     public void populateRooms() {
        prodTable.setRowCount(0);

        ArrayList<Product> flights = this.org.getProductCatalog().getProducts();

        if (flights.size() > 0) {
            for (Product flight : flights) {
                HotelRoomsProduct f = (HotelRoomsProduct) flight.getProductDetails();
                Object[] row = new Object[4];
                row[0] = f;
                row[1] = f.getCity();
                row[2] = f.getRoomType();
                row[3] = f.getRoomsAvailable();
                prodTable.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        flights = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        depCity = new javax.swing.JTextField();
        select = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        desCity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        airline = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        departureDate = new com.toedter.calendar.JDateChooser();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(1300, 553));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "City", "Room Type", "Number of Rooms", "Price"
            }
        ));
        jScrollPane2.setViewportView(flights);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 570, 280));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Hotel Management");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setText("Remove Room");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 130, -1));

        depCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depCityActionPerformed(evt);
            }
        });
        add(depCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 120, -1));

        select.setBackground(new java.awt.Color(204, 255, 204));
        select.setText("Select Room");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 130, 40));

        jLabel4.setText("City");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        jLabel7.setText("Date");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        jLabel8.setText("Number of Rooms");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        desCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desCityActionPerformed(evt);
            }
        });
        add(desCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 120, -1));

        jLabel9.setText("Room Type");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        airline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlineActionPerformed(evt);
            }
        });
        add(airline, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 120, -1));

        jButton6.setBackground(new java.awt.Color(204, 255, 255));
        jButton6.setText("Update Room");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 130, -1));
        add(departureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void depCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depCityActionPerformed

    private void desCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desCityActionPerformed

    private void airlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlineActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        int selectedRow = flights.getSelectedRow();
        FlightTicketProduct f = (FlightTicketProduct) prodTable.getValueAt(selectedRow, 0);
        depCity.setText(f.getDepartureCity());
        airline.setText(f.getAirline());
        departureDate.setDate(f.getDepartureDate());
        desCity.setText(f.getDestinationCity());                                
    }//GEN-LAST:event_selectActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int selectedRow = flights.getSelectedRow();
        FlightTicketProduct f = (FlightTicketProduct) prodTable.getValueAt(selectedRow, 0);
        
        f.setDepartureCity(depCity.getText());
        f.setAirline(airline.getText());
        airline.setText(f.getAirline());
        populateRooms();
        // Others to add
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = flights.getSelectedRow();
        FlightTicketProduct f = (FlightTicketProduct) prodTable.getValueAt(selectedRow, 0);
        this.org.getProductCatalog().getProducts().remove(f);
        populateRooms();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airline;
    private javax.swing.JTextField depCity;
    private com.toedter.calendar.JDateChooser departureDate;
    private javax.swing.JTextField desCity;
    private javax.swing.JTable flights;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton select;
    // End of variables declaration//GEN-END:variables

}
