package UI.OrgManagerWorkArea;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Platform;
import Business.Product.FlightTicketProduct;
import Business.Product.Product;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 15512
 */
public class ManageOrgEmployeeWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrgEmployeeWorkArea
     */
    Platform platform;
    Organization org;
    UserAccount ua;
    JPanel container;
    DefaultTableModel curEmployeeTable;
    DefaultTableModel approveTable;
    Employee selectedEmp;

    public ManageOrgEmployeeWorkArea(Platform platform, JPanel container, UserAccount ua) {
        initComponents();
        this.platform = platform;
        this.ua = ua;
        this.org = platform.findOrgByUserAccount(ua.getUsername(), ua.getPassword());
        this.container = container;
        this.curEmployeeTable = (DefaultTableModel) currentEmployees.getModel();
        this.approveTable = (DefaultTableModel) approveEmployeeTable.getModel();
        populateEmployees();
        populateNewEmployees();
    }

    public void populateEmployees() {
        curEmployeeTable.setRowCount(0);
        ArrayList<Employee> empList = this.org.getEmployeeDirectory().getEmployeelist();
        if (empList.size() > 0) {
            for (Employee emp : empList) {
                if (emp.getApproved()) {
                    Object[] row = new Object[4];
                    row[0] = emp;
                    row[1] = emp.getPerson().getName();
                    row[2] = emp.getUserAccount().getUsername();
                    row[3] = emp.getUserAccount().getPassword();
                    curEmployeeTable.addRow(row);
                }
            }
        }
    }

    public void populateNewEmployees() {
        approveTable.setRowCount(0);
        ArrayList<Employee> empList = this.org.getEmployeeDirectory().getEmployeelist();
        if (empList.size() > 0) {
            for (Employee emp : empList) {
                if (!emp.getApproved()) {
                    Object[] row = new Object[4];
                    row[0] = emp;
                    row[1] = emp.getPerson().getName();
                    row[2] = emp.getUserAccount().getUsername();
                    row[3] = emp.getUserAccount().getPassword();
                    approveTable.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        approveEmployeeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        appBtn = new javax.swing.JButton();
        rejBtn = new javax.swing.JButton();
        remBtn = new javax.swing.JButton();
        password = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        select = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        currentEmployees = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1100, 800));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Airline Employee Management");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 240, -1));

        approveEmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Emp ID", "Name", "Username", "Password"
            }
        ));
        jScrollPane2.setViewportView(approveEmployeeTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 400, 200));

        jLabel1.setText("Password");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        jLabel2.setText("Current Employees");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        appBtn.setBackground(new java.awt.Color(204, 255, 204));
        appBtn.setText("Approve");
        appBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appBtnActionPerformed(evt);
            }
        });
        add(appBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, -1, -1));

        rejBtn.setBackground(new java.awt.Color(255, 204, 204));
        rejBtn.setText("Reject");
        rejBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejBtnActionPerformed(evt);
            }
        });
        add(rejBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, -1, -1));

        remBtn.setBackground(new java.awt.Color(255, 153, 153));
        remBtn.setText("Remove Employee");
        remBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remBtnActionPerformed(evt);
            }
        });
        add(remBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 130, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 120, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 120, -1));

        username.setEditable(false);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 120, -1));

        select.setBackground(new java.awt.Color(204, 255, 204));
        select.setText("Select Employee");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 130, -1));

        jLabel3.setText("New Employee Registration Requests");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, -1));

        jLabel4.setText("Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jLabel5.setText("Username");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        currentEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Emp ID", "Name", "Username", "Password"
            }
        ));
        jScrollPane3.setViewportView(currentEmployees);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 480, 470));

        updateBtn.setBackground(new java.awt.Color(204, 255, 255));
        updateBtn.setText("Update Employee");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nameActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void appBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = approveEmployeeTable.getSelectedRow();
        if (selectedRow > -1) {
        Employee emp = (Employee) approveTable.getValueAt(selectedRow, 0);
            emp.setApproved(true);
            populateEmployees();
            populateNewEmployees();

        } else {
            JOptionPane.showMessageDialog(null, "Select a Employee!");

        }

    }//GEN-LAST:event_appBtnActionPerformed

    private void rejBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = approveEmployeeTable.getSelectedRow();
        if (selectedRow > -1) {
        Employee emp = (Employee) approveTable.getValueAt(selectedRow, 0);
            this.org.getEmployeeDirectory().getEmployeelist().remove(emp);
            //need to delete the user account too
            this.org.getUserAccountDirectory().getUseraccountList().remove(emp.getUserAccount());
            populateNewEmployees();

        } else {
            JOptionPane.showMessageDialog(null, "Select a Employeet!");

        }

    }//GEN-LAST:event_rejBtnActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        int selectedRow = currentEmployees.getSelectedRow();
        if (selectedRow > -1) {
        Employee emp = (Employee) curEmployeeTable.getValueAt(selectedRow, 0);
            name.setText(emp.getPerson().getName());
            username.setText(emp.getUserAccount().getUsername());
            password.setText(emp.getUserAccount().getPassword());
            selectedEmp = emp;

        } else {
            JOptionPane.showMessageDialog(null, "Select a Employee!");

        }

    }//GEN-LAST:event_selectActionPerformed

    private void remBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = currentEmployees.getSelectedRow();
        if (selectedRow > -1) {
        Employee emp = (Employee) curEmployeeTable.getValueAt(selectedRow, 0);
            this.org.getEmployeeDirectory().getEmployeelist().remove(emp);
            //need to delete the user account too
            this.org.getUserAccountDirectory().getUseraccountList().remove(emp.getUserAccount());
            populateEmployees();
            clearTextFields();

        } else {
            JOptionPane.showMessageDialog(null, "Select a Employee!");

        }

    }//GEN-LAST:event_remBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (selectedEmp != null) {
            selectedEmp.getPerson().setName(name.getText());
            selectedEmp.getUserAccount().setUsername(username.getText());
            selectedEmp.getUserAccount().setPassword(password.getText());
            populateEmployees();
            clearTextFields();

        } else {
            JOptionPane.showMessageDialog(null, "Select a Employee!");

        }

    }//GEN-LAST:event_updateBtnActionPerformed

    public void clearTextFields() {
        name.setText("");
        username.setText("");
        password.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appBtn;
    private javax.swing.JTable approveEmployeeTable;
    private javax.swing.JTable currentEmployees;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JButton rejBtn;
    private javax.swing.JButton remBtn;
    private javax.swing.JButton select;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
