/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.OrgManagerWorkArea;

import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Platform;
import Business.Product.FoodServiceProduct;
import Business.Product.InsuranceProduct;
import Business.Product.TravelAgencyProduct;
import Order.Order;
import UserAccount.UserAccount;
import WorkRequest.AirTicketWorkRequest;
import WorkRequest.FoodServiceWorkRequest;
import WorkRequest.InsuranceWorkRequest;
import WorkRequest.TripPlanningWorkRequest;
import WorkRequest.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emi
 */
public class TravelAgencyOrgManagerAllOrdersWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AirlineOrgManagerAllOrdersWorkArea
     */
    Platform platform;
    UserAccount ua;
    JPanel container;
    Organization org;
    DefaultTableModel orderTable;

    public TravelAgencyOrgManagerAllOrdersWorkArea(Platform platform, JPanel container, UserAccount ua) {
        initComponents();
        this.platform = platform;
        this.container = container;
        this.ua = ua;
        this.org = platform.findOrgByUserAccount(ua.getUsername(), ua.getPassword());
        this.orderTable = (DefaultTableModel) queue.getModel();

        populateOrders();
    }

    public void populateOrders() {
        this.org.getWorkQueue();
        orderTable.setRowCount(0);
        ArrayList<WorkRequest> wra = this.org.getWorkQueue().getWorkQueue();
        if (wra.size() > 0) {
            
            for (WorkRequest wr : wra) {
                TripPlanningWorkRequest twr = (TripPlanningWorkRequest) wr;
                Object[] row = new Object[11];
                row[0] = wr;
                row[1] = wr.getOrder();
                row[2] = wr.getCustomer().getPerson().getName();
                row[3] = wr.getOrder().getMainOrderTotal(); //not including other org's price for travel agency revenue
                row[4] = twr.getNeedInsurance();
                row[5] = twr.getIsFullCoverage();
                row[6] = twr.getNeedBooking();
                row[7] = twr.getConfirmedToBook();
                row[8] = wr.getStatus();
                row[9] = wr.getOrder().getOrderApproved();
                //replace row10 with returned plan details
                row[10] = wr.getOrder().getOrderitems().get(0).getSelectedproduct().toString();
                orderTable.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        queue = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        orderIns = new javax.swing.JButton();
        appBtn = new javax.swing.JButton();
        rejBtn = new javax.swing.JButton();
        statusTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        makeBookingBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        queue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "WorkRequest ID", "Order ID", "Customer", "Agency Price", "Insurance Required", "Full Coverage", "Booking Service Required", "Confirmed To Book", "Status", "Order Booked", "Order Details"
            }
        ));
        jScrollPane1.setViewportView(queue);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("WORK QUEUE");

        orderIns.setText("Order Insurance For Customer");
        orderIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderInsActionPerformed(evt);
            }
        });

        appBtn.setText("Approve");
        appBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appBtnActionPerformed(evt);
            }
        });

        rejBtn.setText("Reject");
        rejBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Set Processing Status");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        makeBookingBtn.setText("Make Booking For Customer");
        makeBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeBookingBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 898, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderIns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rejBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusTxt)
                            .addComponent(makeBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderIns)
                        .addGap(18, 18, 18)
                        .addComponent(makeBookingBtn)
                        .addGap(79, 79, 79)
                        .addComponent(statusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(74, 74, 74)
                        .addComponent(appBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rejBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderInsActionPerformed
        // TODO add your handling code here:
        int selectedRow;
        selectedRow = queue.getSelectedRow();
        Boolean needInsurance = (Boolean) orderTable.getValueAt(selectedRow, 4);
        Order order = (Order) orderTable.getValueAt(selectedRow, 1);
        WorkRequest wr = (WorkRequest) orderTable.getValueAt(selectedRow, 0);
        
        if (!needInsurance){
            JOptionPane.showMessageDialog(null, "No insurance required from customer");
        }else{
            //create insurance request
            Order insuranceOrderSentToIns = this.org.getOrderCatalog().createOrder(order.getCustomer());
            TripPlanningWorkRequest travelAgencyWR  = (TripPlanningWorkRequest) wr;
            InsuranceProduct insSelected = (travelAgencyWR.getIsFullCoverage())? new InsuranceProduct("Full Coverage", 300):new InsuranceProduct("Partial Coverage", 200);
            insuranceOrderSentToIns.newOrderItem(insSelected);
            InsuranceWorkRequest inswr = order.getOrderWorkQueue().newInsuranceWorkRequest(insuranceOrderSentToIns,order.getCustomer(),this.ua,this.platform);
            
            //link this request with customer's main trip planning order and request
            inswr.setCustomerTravelAgencyOrder(order);
            inswr.setCustomerTripPlanningRequest(travelAgencyWR);
            
            wr.setStatus("Booking insurance from insurance advisor");
            JOptionPane.showMessageDialog(null, "Insurance request sent");
            
            populateOrders();
        }
    }//GEN-LAST:event_orderInsActionPerformed

    private void appBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow;
        selectedRow = queue.getSelectedRow();
        WorkRequest wr = (WorkRequest) orderTable.getValueAt(selectedRow, 0);
        if (wr.getStatus().equalsIgnoreCase("Work Request Finished") || wr.getStatus().equalsIgnoreCase("Work Request Rejected")){
            JOptionPane.showMessageDialog(null, "Processing already completed");
        }else{
            this.org.getWorkQueue().finishWorkRequest(wr);
            populateOrders();
        }
        
    }//GEN-LAST:event_appBtnActionPerformed

    private void rejBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejBtnActionPerformed
        // TODO add your handling code here:'
        int selectedRow;
        selectedRow = queue.getSelectedRow();
        WorkRequest wr = (WorkRequest) orderTable.getValueAt(selectedRow, 0);
        if (wr.getStatus().equalsIgnoreCase("Work Request Finished") || wr.getStatus().equalsIgnoreCase("Work Request Rejected")){
            JOptionPane.showMessageDialog(null, "Processing already completed");
        }else{
            this.org.getWorkQueue().rejectWorkRequest(wr);
            populateOrders();
        }
    }//GEN-LAST:event_rejBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow;
        selectedRow = queue.getSelectedRow();
        WorkRequest wr = (WorkRequest) orderTable.getValueAt(selectedRow, 0);
        wr.setStatus(statusTxt.getText());
        populateOrders();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void makeBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeBookingBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow;
        selectedRow = queue.getSelectedRow();
        Boolean needBooking = (Boolean) orderTable.getValueAt(selectedRow, 6);
        Boolean confirmBooking = (Boolean) orderTable.getValueAt(selectedRow, 7);
        Order order = (Order) orderTable.getValueAt(selectedRow, 1);
        WorkRequest wr = (WorkRequest) orderTable.getValueAt(selectedRow, 0);
        
        if(!needBooking){
            JOptionPane.showMessageDialog(null, "This is a trip consulting request");
        }else if(needBooking && !confirmBooking){
            JOptionPane.showMessageDialog(null, "Wait for customer to confirm budget");
        }else{
            //send booking requests, wait for the plan detail from Saaketh
            wr.setStatus("Making reservations for the trip");
            JOptionPane.showMessageDialog(null, "Booking requests sent");
        }
    }//GEN-LAST:event_makeBookingBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makeBookingBtn;
    private javax.swing.JButton orderIns;
    private javax.swing.JTable queue;
    private javax.swing.JButton rejBtn;
    private javax.swing.JTextField statusTxt;
    // End of variables declaration//GEN-END:variables
}
