/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerWorkArea;

import Business.Customer.Customer;
import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Platform;
import Business.Product.FlightTicketProduct;
import Business.Product.HotelRoomsProduct;
import Business.Product.Product;
import Order.Order;
import UserAccount.UserAccount;
import Validation.VerifyNull;
import WorkRequest.HotelBookingWorkRequest;
import WorkRequest.TripPlanningWorkRequest;
import WorkRequest.WorkRequest;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emi
 */
public class BookHotelJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookFlightJPanel
     */
    Platform platform;
    UserAccount ua;
    JPanel container;
    DefaultTableModel resultTable;
    Organization org;
    Customer cus;
    HotelRoomsProduct roomSelected;
    Employee emp;
    Boolean isEmp;
    TripPlanningWorkRequest trp;

    public BookHotelJPanel(JPanel container, Platform platform, UserAccount ua) {
        initComponents();
        this.platform = platform;
        this.container = container;
        this.ua = ua;
        this.org = this.platform.getHotelOrg();
        this.isEmp = false;
        this.resultTable = (DefaultTableModel) rooms.getModel();
        this.cus = this.platform.getCustomerDirectory().findCustomerById(ua.getAccountId());
    }

//    public BookHotelJPanel(Platform platform, UserAccount ua) {
//        initComponents();
//        this.platform = platform;
//        this.ua = ua;
//        this.org = this.platform.getHotelOrg(); //hotel
//        this.resultTable = (DefaultTableModel) rooms.getModel();
//        this.emp = this.platform.getTravelAgencyOrg().getEmployeeDirectory().findById(ua.getAccountId());
//    }

    public BookHotelJPanel(Platform platform, UserAccount ua, TripPlanningWorkRequest wr) {
        initComponents();
        this.platform = platform;
        this.ua = ua;
        this.isEmp = true;
        this.org = this.platform.getHotelOrg();
        this.resultTable = (DefaultTableModel) rooms.getModel();
        this.emp = this.platform.getTravelAgencyOrg().getEmployeeDirectory().findById(ua.getAccountId());
        this.trp = wr;
        this.bookBtn.setText("Add to Customer Plan");
        this.desCity.setText(wr.getDesCity());
        this.checkIn.setDate(wr.getDepDate());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        desCity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        checkIn = new com.toedter.calendar.JDateChooser();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rooms = new javax.swing.JTable();
        selectBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        bookBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        checkOut = new com.toedter.calendar.JDateChooser();
        roomsCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Destination City");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        add(desCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 113, -1));

        jLabel3.setText("Check-in Date");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        checkIn.setDateFormatString("yyyy-MM-dd");
        add(checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 158, -1));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        rooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Room ID", "Destination City", "Room Type", "Price"
            }
        ));
        jScrollPane2.setViewportView(rooms);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 880, 420));

        selectBtn.setText("Select");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });
        add(selectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, -1, -1));

        jLabel5.setText("Hotel Selected");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, -1, 20));

        jTextField3.setEditable(false);
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 105, -1));

        jLabel6.setText("Total Price");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, -1, 20));

        jTextField4.setEditable(false);
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 650, 105, -1));

        bookBtn.setText("Book");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });
        add(bookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 650, -1, -1));

        jLabel7.setText("Stay");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, 35, 20));

        jTextField5.setEditable(false);
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, 30, -1));

        jLabel8.setText("days");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 30, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hotel_128px.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 138, 136));

        jLabel10.setText("Check-out Date");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        checkOut.setDateFormatString("yyyy-MM-dd");
        add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 158, -1));

        roomsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        roomsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomsComboActionPerformed(evt);
            }
        });
        add(roomsCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 130, -1));

        jLabel1.setText("Rooms");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 120, -1));

        jLabel11.setText("Rooms");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 50, 20));

        jTextField7.setEditable(false);
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 30, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        resultTable.setRowCount(0);

        ArrayList<Product> searchResult = new ArrayList<Product>();

        String des = desCity.getText();
        Date indate = checkIn.getDate();
        Date outdate = checkOut.getDate();
//        int rooms = (int) roomsCombo.getSelectedItem();
        VerifyNull checkNull = new VerifyNull();
        boolean nonull = checkNull.checkNullObject(des,indate,outdate);
        
        if(nonull){
        for (Product room : this.org.getProductCatalog().getProducts()) {
            HotelRoomsProduct r = (HotelRoomsProduct) room.getProductDetails();
            if (r.getCity().equalsIgnoreCase(des) //                    && f.getDepartureDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate().
                    //                            equals(date.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate())
                    ) {
                searchResult.add(room);
            }
        }

        if (searchResult.size() > 0) {
            for (Product roomFound : searchResult) {
                HotelRoomsProduct r = (HotelRoomsProduct) roomFound.getProductDetails();
                Object[] row = new Object[4];
                row[0] = r;
                row[1] = r.getCity();
//                row[4] = new SimpleDateFormat("yyyy-MM-dd").format(f.getDepartureDate());
                row[2] = r.getRoomType();

                row[3] = r.getPrice();
                resultTable.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Oops...no hotel found");
        }
        }

    }//GEN-LAST:event_searchBtnActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = rooms.getSelectedRow();

        if(selectedRow>=0){
            this.roomSelected = (HotelRoomsProduct) resultTable.getValueAt(selectedRow, 0);

            jTextField3.setText(roomSelected.getProductId());

            Instant checkindate = checkIn.getDate().toInstant();
            Instant checkoutdate = checkOut.getDate().toInstant();
            Long durationSeconds = Duration.between(checkindate, checkoutdate).getSeconds();
            jTextField5.setText(String.valueOf((int) TimeUnit.DAYS.convert(durationSeconds, TimeUnit.SECONDS))); //stay duration

            jTextField7.setText(String.valueOf(roomsCombo.getSelectedItem())); //rooms
            //unit price*rooms*nights
            jTextField4.setText(String.valueOf(roomSelected.getPrice() * Integer.valueOf(jTextField5.getText()) * Integer.valueOf(jTextField7.getText())));
        }else{
             JOptionPane.showMessageDialog(null, "select a product");
        }
        
    }//GEN-LAST:event_selectBtnActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        // TODO add your handling code here:
        if (this.roomSelected != null) {
             if (this.isEmp) {
                trp.addToTripDetails(roomSelected);
                JOptionPane.showMessageDialog(null, "Added to trip details");

            }else{
                //create order for customer and add to customer's order list
                Order o = this.cus.getCustomerOrderCatalog().createOrder(cus);
                //link product with the order
                for (int i = 0; i < Integer.valueOf(jTextField5.getText()) * Integer.valueOf(jTextField7.getText()); i++) {
                    o.newOrderItem(this.roomSelected);
                }

                HotelBookingWorkRequest workReq = o.getOrderWorkQueue().newHotelBookingWorkRequest(o, this.cus, this.cus.getUserAccount(), this.platform);
//        this.org.getWorkQueue().addWorkRequest(workReq);
                //add the order to org's order list
//        this.org.getOrderCatalog().getOrders().add(o);
                JOptionPane.showMessageDialog(null, "Booking request sent");
                
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField7.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a product!");

        }
    }//GEN-LAST:event_bookBtnActionPerformed

    private void roomsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomsComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomsComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private com.toedter.calendar.JDateChooser checkIn;
    private com.toedter.calendar.JDateChooser checkOut;
    private javax.swing.JTextField desCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTable rooms;
    private javax.swing.JComboBox<String> roomsCombo;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton selectBtn;
    // End of variables declaration//GEN-END:variables
}
