/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerWorkArea;

import Business.Customer.Customer;
import Business.Organization.Organization;
import Business.Platform;
import Business.Product.HotelRoomsProduct;
import Business.Product.Product;
import Order.Order;
import UserAccount.UserAccount;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emi
 */
public class BookHotelJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookFlightJPanel
     */
    Platform platform;
    UserAccount ua;
    JPanel container;
    DefaultTableModel resultTable;
    Organization org;
    Customer cus;
    HotelRoomsProduct roomSelected;
    public BookHotelJPanel(JPanel container, Platform platform, UserAccount ua) {
        initComponents();
        this.platform = platform; 
        this.container = container;
        this.ua = ua;
        this.org = this.platform.getHotelOrg();
        this.resultTable = (DefaultTableModel) rooms.getModel();
        this.cus = this.platform.getCustomerDirectory().findCustomerById(ua.getAccountId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        desCity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        checkIn = new com.toedter.calendar.JDateChooser();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rooms = new javax.swing.JTable();
        selectBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        bookBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        checkOut = new com.toedter.calendar.JDateChooser();
        roomsCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Destination City");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        add(desCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 113, -1));

        jLabel3.setText("Check-in Date");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        checkIn.setDateFormatString("yyyy-MM-dd");
        add(checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 158, -1));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        rooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Room ID", "Destination City", "Room Type", "Price"
            }
        ));
        jScrollPane2.setViewportView(rooms);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 880, 420));

        selectBtn.setText("Select");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });
        add(selectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, -1, -1));

        jLabel5.setText("Hotel Selected");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 690, -1, 20));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 690, 105, -1));

        jLabel6.setText("Total Price");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 690, -1, 20));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 690, 105, -1));

        bookBtn.setText("Book");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });
        add(bookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 690, -1, -1));

        jLabel7.setText("Stay");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 690, 35, 20));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 690, 30, -1));

        jLabel8.setText("days");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 690, 30, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hotel_128px.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 138, 136));

        jLabel10.setText("Check-out Date");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        checkOut.setDateFormatString("yyyy-MM-dd");
        add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 158, -1));

        roomsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        add(roomsCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 130, -1));

        jLabel1.setText("Rooms");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 120, -1));

        jLabel11.setText("Rooms");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, 50, 20));
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 690, 30, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        resultTable.setRowCount(0);
        
        ArrayList<Product> searchResult = new ArrayList<Product>();
        
        String des = desCity.getText();
//        Date indate = checkIn.getDate();
//        Date outdate = checkOut.getDate();
//        int rooms = (int) roomsCombo.getSelectedItem();
        
        for (Product room: this.org.getProductCatalog().getProducts()){
            HotelRoomsProduct r = (HotelRoomsProduct) room.getProductDetails();
            if ( r.getCity().equalsIgnoreCase(des) 
//                    && f.getDepartureDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate().
//                            equals(date.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate())
                    ){
                searchResult.add(room);
            }
        }
        
        if(searchResult.size()>0){
            for (Product roomFound: searchResult){
                HotelRoomsProduct r = (HotelRoomsProduct) roomFound.getProductDetails();
                Object[] row = new Object[4];
                row[0] = r;
                row[1] = r.getCity();
//                row[4] = new SimpleDateFormat("yyyy-MM-dd").format(f.getDepartureDate());
                row[2] = r.getRoomType();

                row[3] = r.getPrice();
                resultTable.addRow(row);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Oops...no hotel found");
        }    

    }//GEN-LAST:event_searchBtnActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = rooms.getSelectedRow();
        this.roomSelected = (HotelRoomsProduct) resultTable.getValueAt(selectedRow, 0);
        
        jTextField3.setText(roomSelected.getProductId());
        
        Instant checkindate = checkIn.getDate().toInstant();
        Instant checkoutdate = checkOut.getDate().toInstant();
        Long durationSeconds = Duration.between(checkindate,checkoutdate).getSeconds();
        jTextField5.setText(String.valueOf( (int)TimeUnit.DAYS.convert(durationSeconds,TimeUnit.SECONDS))); //stay duration
        
        jTextField7.setText(String.valueOf(roomsCombo.getSelectedItem())); //rooms
        //unit price*rooms*nights
        jTextField4.setText(String.valueOf(roomSelected.getPrice()*Integer.valueOf(jTextField5.getText())*Integer.valueOf(jTextField7.getText()))); 
    }//GEN-LAST:event_selectBtnActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        // TODO add your handling code here:
        //create order for customer and add to customer's order list
        Order o = this.cus.getCustomerOrderCatalog().createOrder(cus);
        //link product with the order
        for (int i=0; i< Integer.valueOf(jTextField5.getText())*Integer.valueOf(jTextField7.getText()); i++){
            o.newOrderItem(this.roomSelected);
        }
        //add the order to org's order list
        this.org.getOrderCatalog().getOrders().add(o);
        JOptionPane.showMessageDialog(null, "Successfully booked");
    }//GEN-LAST:event_bookBtnActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private com.toedter.calendar.JDateChooser checkIn;
    private com.toedter.calendar.JDateChooser checkOut;
    private javax.swing.JTextField desCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTable rooms;
    private javax.swing.JComboBox<String> roomsCombo;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton selectBtn;
    // End of variables declaration//GEN-END:variables
}
