/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerWorkArea;

import Business.Customer.Customer;
import Business.Organization.Organization;
import Business.Platform;
import Business.Product.AttractionProduct;
import Business.Product.FlightTicketProduct;
import Business.Product.Product;
import Order.Order;
import UserAccount.UserAccount;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emi
 */
public class BookAttractionTicketJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookFlightJPanel
     */
    Platform platform;
    UserAccount ua;
    JPanel container;
    DefaultTableModel resultTable;
    Organization org;
    Customer cus;
    AttractionProduct attrctionSelected;
    public BookAttractionTicketJPanel(JPanel container, Platform platform, UserAccount ua) {
        initComponents();
        this.platform = platform; 
        this.container = container;
        this.ua = ua;
        this.org = this.platform.getAttractionOrg();
        this.resultTable = (DefaultTableModel) att.getModel();
        this.cus = this.platform.getCustomerDirectory().findCustomerById(ua.getAccountId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        desCity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        depDate = new com.toedter.calendar.JDateChooser();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        att = new javax.swing.JTable();
        selectBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        bookBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        visitorsCombo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Destination City");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        add(desCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, -1));

        jLabel3.setText("Date");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        depDate.setDateFormatString("yyyy-MM-dd");
        add(depDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 158, -1));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

        att.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tourist Attraction Ticket ID", "Ticket Type", "City", "Price"
            }
        ));
        jScrollPane2.setViewportView(att);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 880, 370));

        selectBtn.setText("Select");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });
        add(selectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, -1, -1));

        jLabel5.setText("Ticket Selected");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, -1, 20));

        jTextField3.setEditable(false);
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 105, -1));

        jLabel6.setText("Number of Visitors");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, 20));

        jTextField4.setEditable(false);
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 105, -1));

        bookBtn.setText("Book");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });
        add(bookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 650, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/attraction_128px.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 130, 130));

        jLabel10.setText("Total Price");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, -1, 20));

        visitorsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        add(visitorsCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        resultTable.setRowCount(0);
        
        ArrayList<Product> searchResult = new ArrayList<Product>();
        
        String des = desCity.getText();
        
        for (Product att: this.org.getProductCatalog().getProducts()){
            AttractionProduct ap = (AttractionProduct) att.getProductDetails();
            if (ap.getCity().equalsIgnoreCase(des)){
                searchResult.add(att);
            }
        }
        
        if(searchResult.size()>0){
            for (Product attFound: searchResult){
                AttractionProduct att = (AttractionProduct) attFound.getProductDetails();
                Object[] row = new Object[4];
                row[0] = att;
                row[1] = att.getTicketType();
                row[2] = att.getCity();
                row[3] = att.getPrice();
                resultTable.addRow(row);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Oops...no ticket found");
        }    

    }//GEN-LAST:event_searchBtnActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = att.getSelectedRow();
        this.attrctionSelected = (AttractionProduct) resultTable.getValueAt(selectedRow, 0);
        jTextField3.setText(attrctionSelected.getProductId());
        String num = String.valueOf(visitorsCombo.getSelectedItem());
        jTextField4.setText(String.valueOf(attrctionSelected.getPrice()*Integer.valueOf(num)));
    }//GEN-LAST:event_selectBtnActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        // TODO add your handling code here:
        //create order for customer and add to customer's order list
        Order o = this.cus.getCustomerOrderCatalog().createOrder(cus);
        //link product with the order
        o.newOrderItem(this.attrctionSelected);
        //add the order to org's order list
        this.org.getOrderCatalog().getOrders().add(o);
        JOptionPane.showMessageDialog(null, "Booking request sent");
    }//GEN-LAST:event_bookBtnActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable att;
    private javax.swing.JButton bookBtn;
    private com.toedter.calendar.JDateChooser depDate;
    private javax.swing.JTextField desCity;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton selectBtn;
    private javax.swing.JComboBox<String> visitorsCombo;
    // End of variables declaration//GEN-END:variables
}
