/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerWorkArea;

import Business.Customer.Customer;
import Business.Organization.Organization;
import Business.Platform;
import Business.Product.FlightTicketProduct;
import Order.Order;
import Order.OrderItem;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emi
 */
public class ViewOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrdersJPanel
     */
    
    Platform platform;
    UserAccount ua;
    JPanel container;
    DefaultTableModel ordersTable;
    Organization org;
    Customer cus;
    public ViewOrdersJPanel(JPanel container, Platform platform, UserAccount ua) {
        initComponents();
        this.platform = platform; 
        this.container = container;
        this.ua = ua;
        this.org = this.platform.getAirlineOrg();
        this.ordersTable = (DefaultTableModel) orders.getModel();
        this.cus = this.platform.getCustomerDirectory().findCustomerById(ua.getAccountId());
        
        populateOrders();
    }
    
    public void populateOrders(){
        ordersTable.setRowCount(0);
        
        ArrayList<Order> allOrders = this.cus.getCustomerOrderCatalog().getOrders();
        
        if(allOrders.size()>0){
            for (Order o: allOrders){
                for (OrderItem oi: o.getOrderitems()){
                    Object[] row = new Object[3];
                    row[0] = o.getOrderId();
                    row[1] = oi.getSelectedproduct();
                    row[2] = o.getOrderTotal();
                    ordersTable.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orders = new javax.swing.JTable();

        orders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Product ID", "Price"
            }
        ));
        jScrollPane1.setViewportView(orders);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orders;
    // End of variables declaration//GEN-END:variables
}
